### ISSUE TITLE
D1 type error

### ISSUE THREAD

**Issue by tom-huntington** [james-elicx/cf-bindings-proxy#8]
I got KV working in an astro site created with `npm create cloudflare@latest`.

But D1 gives me the following error
> [mf:inf] POST / 500 Internal Server Error (2ms)
TypeError: e[r] is not a function
    at bundledWorker-0.33191269954773306.js:107:61
    at Array.reduce (<anonymous>)
    at c (bundledWorker-0.33191269954773306.js:107:21)
    at Object.fetch (bundledWorker-0.33191269954773306.js:115:145)
    at async jsonError (bundledWorker-0.33191269954773306.js:143:12)
    at async jsonError2 (bundledWorker-0.33191269954773306.js:256:12) {
  stack: TypeError: e[r] is not a function
    at bundledWo…or2 (bundledWorker-0.33191269954773306.js:256:12),
  message: e[r] is not a function
}

```
const d1 = await binding<D1Database>('DB');
console.log(d1);
const q = await d1
		.prepare("SELECT * FROM Board")
                .all();
console.log(q);
```

Also, I thought astro's `pages:dev` command (`"wrangler pages dev --compatibility-date=2023-07-15 --proxy 3000 -- astro dev"`) would be able access the bindings directly but I found out the hardway that they couldn't https://github.com/withastro/roadmap/discussions/590

**Comment by james-elicx** [comment]
Hey there, can you just confirm if you're using the latest version? I believe I might have fixed this in 0.2.2

**Comment by tom-huntington** [comment]
I'm using `0.2.2`

**Comment by james-elicx** [comment]
Thanks. I've just got home and am able to test this now.

The reason is because of the `await binding<D1Database>('DB');`. The await here is unnecessary and has no effect. Only the actual call on the binding needs to be awaited, like if you were doing `await binding('DB').prepare("SELECT * FROM Board").all();`.

I can add a fix to allow you to do it in that way (`await binding('DB');`) if you would like, but you don't need to do that.

**Comment by tom-huntington** [comment]
> I can add a fix to allow you to do it in that way (`await binding('DB');`

Maybe a better error message? But I think this github issue should be sufficient.

Anyway thanks for this! Do you know which frameworks *do support Cloudflare bindings in a fast HMR environment*. I believe I've confirmed remix does
